services:
  jira:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira
    environment:
      JVM_MAXIMUM_MEMORY: 2G
      ATL_TOMCAT_PORT: 80
    ports:
      - "8000:80"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: jiradb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33036:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jiraVolume:
  mysql-data: