services:
  jira:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira
    environment:
      JVM_MAXIMUM_MEMORY: 2G
      ATL_PROXY_NAME: jira.example.fr
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: true
    ports:
      - "8080:8080"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    networks:
      - app-network


  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
     - "80:80"
     - "443:443"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: jiradb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "33036:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jiraVolume:
  mysql-data: